node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     dir("${env.WORKSPACE}/basics"){

       docker.withRegistry('https://index.docker.io/v1/', 'dockermikeb') {
         def app = docker.build("mikebenari/docker-nodejs-demo:${commit_id}", '.').push()
         def app_1 = docker.build("mikebenari/docker-nodejs-demo:latest", '-f Dockerfile .').push()
       }
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 mikebenari/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

